"""Finding type and severity enumerations."""
from __future__ import annotations

import enum


class Severity(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class FindingType(str, enum.Enum):
    HIGH_NULLABILITY = "HIGH_NULLABILITY"
    CONSTANT_COLUMN = "CONSTANT_COLUMN"
    ID_COLUMN_DETECTED = "ID_COLUMN_DETECTED"
    INVALID_RANGE_VALUES = "INVALID_RANGE_VALUES"
    IMBALANCED_DISTRIBUTION = "IMBALANCED_DISTRIBUTION"
    HIGH_OUTLIER_DENSITY = "HIGH_OUTLIER_DENSITY"
    STRONG_CORRELATION = "STRONG_CORRELATION"
    SKEWED_DISTRIBUTION = "SKEWED_DISTRIBUTION"
    MIXED_TYPE_COLUMN = "MIXED_TYPE_COLUMN"
    DUPLICATE_ROWS = "DUPLICATE_ROWS"
    POTENTIAL_LEAKAGE = "POTENTIAL_LEAKAGE"
    SEMANTIC_TAG = "SEMANTIC_TAG"
    DATA_RECOMMENDATION = "DATA_RECOMMENDATION"
